#ifndef __TAGLIST_H__
#define __TAGLIST_H__

#include "cocos2d.h"
#include "GameData.h"

USING_NS_CC;

#define TAG_SPRITE_PLAYER			1000
#define TAG_SPRITE_ENEMY			2000		// 2000 ~ 3000 사이가 적 비행기
#define TAG_MOVE_ACTION				4000

#define PADDING_SCREEN				10

#define TAG_GAME_LABEL_SCORE		50
#define TAG_GAME_LABEL_BUFFITEM		51
#define	TAG_GAME_LABEL_DEBUFFITEM	52

#define TAG_MENU					60			// 60~64 메뉴 화면 테그 
#define TAG_HELP_MENU_NEXT			65			// 65~69 헬프 화면 테그 
#define TAG_HELP_MENU_BACK			66

#define TAG_DATA_MENU_NEXT			67			
#define TAG_DATA_MENU_BACK			68
#define TAG_DATA_MENU_TIME			69
#define TAG_DATA_MENU_SCORE			70
#define TAG_DATA_MENU_BUF			71
#define TAG_DATA_MENU_DEBUF			72
#define TAG_DATA_LABEL_TIME			73
#define TAG_DATA_LABEL_SCORE		74
#define TAG_DATA_LABEL_BUF			75
#define TAG_DATA_LABEL_DEBUF		76

#define TAG_OPTION_MENU_BACK		77
#define TAG_OPTION_MENU_MUSIC		78
#define TAG_OPTION_MENU_EFFECT		79
#define TAG_OPTION_MENU_DELETE		80
#define TAG_OPTION_LABEL_MUSIC		81
#define	TAG_OPTION_LABEL_EFFECT		82


#endif // __TAGLIST_H__
